import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from '../components/Navbar';
import Heroheader from '../components/Heroheader';
import Featured from '../components/Featured';
import Shopmen from '../components/Shopmen';
import Socialbar from '../components/Socialbar';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rebel- Let your clothing speak for you</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/w-rebel.png" />
      </Head>
      <Navbar></Navbar>
      <Heroheader></Heroheader>
      <Featured></Featured>
      <Shopmen></Shopmen>
      <Socialbar></Socialbar>
      <Footer></Footer>
    </>
  );
}
